modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="bitems" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Bitems: Bilingual Items" #mandatory
authors="Exokem" #optional
description='''
Adds item name and tooltip translations of a specified language into all item hovered tooltips.
'''
[[dependencies.bitems]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="CLIENT"
[[dependencies.bitems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="CLIENT"
